version: "3"

services:
  database:
    image: mysql:5.7
    container_name: desafio2_database
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./docker/database:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio2
    networks:
      - desafio2_network

  web:
    image: desafio2_web
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    container_name: desafio2_web
    restart: unless-stopped
    tty: true
    ports:
      - 8080:80
    networks:
      - desafio2_network

  app:
    image: desafio2_app
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    container_name: desafio2_app
    restart: unless-stopped
    depends_on:
      - database
      - web
    tty: true
    networks:
      - desafio2_network

#Docker Networks
networks:
  desafio2_network:
    driver: bridge
